name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci